@startuml
'https://plantuml.com/class-diagram


Solution43 *-- CreateDirectory

class CreateDirectory{
String path

+makeDirectory(String siteName, String author, String jsFolder, String cssFolder)
+printOutput(String index, String js, String css)
+String createCSS(String siteName, String directory, String cssFolder)
+createJS(String siteName, String directory, String jsFolder)
+createHTML(String directory, String siteName, String author)
+createFolder(String siteName)
}
class Solution43{
String siteName
String cssFolder
String jsFolder
String siteName
String author
+getInput(String prompt)
}
@enduml