@startuml
'https://plantuml.com/class-diagram


Solution46 *-- WordSearch

class WordSearch {
Map hashMap
Map<String, String> sorted
+ readInput()
+ createTreeMap(Map hashMap)
+ getOutput(Map hashMap, Map<String, String> sorted)
+ getStars(Object o)
+ getDirectory()
}

class Solution46{
}

@enduml