@startuml
'https://plantuml.com/class-diagram

Solution41 *--  Sort
Sort *-- Output

class Solution41 {
ArrayList<String> input

+ readInput()
}

class Sort{
+rearrange(ArrayList<String> unsortedArray)
}

class Output{
+ printOutput(ArrayList<String> sortedArray)
}
@enduml