@startuml
'https://plantuml.com/class-diagram


InputOutput *-- Split
Split *-- InputOutput


class InputOutput {
ArrayList<String> input
+ readInput()
+ printOutput(ArrayList<String> sorted)
}

class Split{
 ArrayList <String> output
+replaceCommas(ArrayList<String> unparsed)
}

@enduml